### ISSUE TITLE
token based fees

### ISSUE THREAD

**Issue by devtooligan** [alcueca/erc7399-reference#2]
https://github.com/alcueca/erc7399/blob/56ba9dfdee8ad34150bc77de2bb67c950a1bb415/src/FlashLender.sol#L14

idk if it's too much of an implementation detail for the EIP, but you could offer token-based fees (instead of one fee for all tokens) by having this `supportedTokens` mapping be a mapping of address --> SupportedToken struct.  If a uint type less than 256 bits is chosen, then both would fit in a single word which could be read by a single SLOAD.

```
struct SupportedToken {
  bool enabled;
  uint128 fee;
}

**Comment by alcueca** [comment]
It is difficult to make a reference implementation that is complex enough to show the features, but simple enough to be understood.

I think it is ok to have fee-per-token in the reference implementation. I did it so that there are 29 bytes left for other token-specific data.
